// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiCcVxRkQHnGucA_3FL5XeTp7aiX0wbyU',
    appId: '1:603282217452:web:ef9e9d09d824fbc8c308c9',
    messagingSenderId: '603282217452',
    projectId: 'bino-cea94',
    authDomain: 'bino-cea94.firebaseapp.com',
    storageBucket: 'bino-cea94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkXVTUqlRuG3cwn7L96EYVOamyYH0KypM',
    appId: '1:603282217452:android:8d4157762e972687c308c9',
    messagingSenderId: '603282217452',
    projectId: 'bino-cea94',
    storageBucket: 'bino-cea94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYBLnd3sksDKRrVxhBGKmAIpLTYVj40Xc',
    appId: '1:603282217452:ios:4ea1dfd42f5172f9c308c9',
    messagingSenderId: '603282217452',
    projectId: 'bino-cea94',
    storageBucket: 'bino-cea94.appspot.com',
    iosClientId: '603282217452-9ehj3qrookgp0onl9fbj50qb1b2l7nbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.bino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYBLnd3sksDKRrVxhBGKmAIpLTYVj40Xc',
    appId: '1:603282217452:ios:4ea1dfd42f5172f9c308c9',
    messagingSenderId: '603282217452',
    projectId: 'bino-cea94',
    storageBucket: 'bino-cea94.appspot.com',
    iosClientId: '603282217452-9ehj3qrookgp0onl9fbj50qb1b2l7nbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.bino',
  );
}
